# Generated by Django 3.2.7 on 2021-09-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLient',
            new_name='Clientes',
        ),
    ]
